name = "DecisionProblem"
uuid = "a2308b2c-a7fc-48d4-b4d5-6ad1bdbbf0f0"
authors = ["James Doss-Gollin <jdossgollin@rice.edu>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
